#!/bin/bash
# to list all monitors available type: xrandr -q
monitorLeft="DVI-D-0"
monitorRight="DP-2"
case "$1" in
off)
  $0 right-off
#  $0 left-off
;;

on)
  $0 right-on
  $0 left-on
;;

setup)
  $0 left-off
  $0 right-on
;;

left-off)
  xrandr --output $monitorRight --off
;;

right-off)
  xrandr --output $monitorLeft --off
;;

left-on)
#  echo 'xrandr --output DP-0 --mode 2560x1440 --rate 144.00 --left-of DVI-D-0'
  xrandr --output $monitorRight --mode 1920x1080 --left-of $monitorLeft
;;

right-on)
  xrandr --output $monitorLeft --primary --mode 2560x1440 --rate 144.00 --right-of $monitorRight
;;

*)
  xrandr --output $monitorRight --primary --mode 2560x1440 --rate 144.00 --right-of $monitorLeft
  xrandr --output $monitorLeft --mode 1920x1080 --left-of $monitorRight

;;
esac
exit 0;
