#!/bin/bash
# to list all monitors available type: xrandr -q
monitorLeft="DP-0"
monitorRight="DVI-D-0"
case "$1" in
off)
  $0 right-off
#  $0 left-off
;;

on)
  $0 right-on
  $0 left-on
;;

setup)
  $0 left-on
  $0 right-off
;;

left-off)
  xrandr --output $monitorLeft --off
;;

right-off)
  xrandr --output $monitorRight --off
;;

left-on)
  #bug
  #xrandr --output $monitorLeft --mode 2560x1440 --rate 144.00 --left-of $monitorRight
  echo 'xrandr --output DP-0 --mode 2560x1440 --rate 144.00 --left-of DVI-D-0'
;;

right-on)
  xrandr --output $monitorRight --mode 1920x1080 --right-of $monitorLeft
;;

*)

;;
esac
exit 0;
